# Generated by Django 5.2 on 2026-09-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('lead_generated_through', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Outbound Calls', 'Outbound Calls'), ('Reference', 'Reference'), ('Field Sales', 'Field Sales'), ('Justdial', 'Justdial')], max_length=40)),
                ('sales_closed_by', models.CharField(blank=True, max_length=120)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('packing_type', models.CharField(blank=True, max_length=100)),
                ('no_of_pieces', models.PositiveIntegerField(default=0)),
                ('weight_tons', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('vehicle_type', models.CharField(max_length=80)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('driver_number', models.CharField(blank=True, max_length=20)),
                ('owner_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_sourced_by', models.CharField(choices=[('Direct', 'Direct'), ('Broker', 'Broker')], default='Direct', max_length=20)),
                ('owner_broker_name', models.CharField(blank=True, max_length=150)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loading_unloading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('halting_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='onepage_order.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_through', models.CharField(blank=True, choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('CASH', 'CASH'), ('IMPS', 'IMPS'), ('UPI', 'UPI')], max_length=20)),
                ('utr_details', models.CharField(blank=True, max_length=150)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='onepage_order.order')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Balance', 'Balance'), ('Others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_payments', to='onepage_order.order')),
            ],
        ),
    ]
