# Generated by Django 5.2 on 2026-09-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_order', '0002_order_account_name_order_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('request_url', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('TRACKING', 'Tracking'), ('CONSENT', 'Consent')], max_length=20, unique=True)),
                ('access_token', models.TextField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_reference', models.CharField(max_length=100, unique=True)),
                ('driver_mobile', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('not_enabled', 'Not Enabled'), ('imported', 'Imported'), ('sms_sent', 'SMS Sent'), ('consent_received', 'Consent Received'), ('waiting_location', 'Waiting Location'), ('active', 'Live Tracking'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('deleted', 'Deleted'), ('license_hold', 'License Hold'), ('expired', 'Consent Expired'), ('error', 'Error')], default='not_enabled', max_length=20)),
                ('consent_received', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('location_status', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_session', to='onepage_order.order')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('sms_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='onepage_order.trackingsession')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked', models.BooleanField(default=False)),
                ('location_status', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='onepage_order.trackingsession')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
