# Generated by Django 5.2 on 2026-09-11 11:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_order', '0003_apilog_apitoken_trackingsession_smslog_livelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='total_selling_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_payment_type',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Topay', 'Topay'), ('TBB', 'TBB')], max_length=20),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('vehicle_placed', 'Vehicle Placed'), ('live_tracking', 'Live Tracking Enabled'), ('vehicle_document', 'Vehicle Document'), ('invoice_eway', 'Invoice / E-way'), ('advance_to_fleet', 'Advance To Fleet'), ('fleet_departed', 'Fleet Departed'), ('balance_trans_fleet', 'Balance Transfer To Fleet'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('pod_received', 'POD Received'), ('settled', 'Settled'), ('lr_generated', 'LR Generated')], default='vehicle_placed', max_length=50)),
                ('vehicle_placed', models.BooleanField(default=False)),
                ('vehicle_document', models.BooleanField(default=False)),
                ('invoice_eway', models.BooleanField(default=False)),
                ('advance_to_fleet', models.BooleanField(default=False)),
                ('balance_to_fleet', models.BooleanField(default=False)),
                ('fleet_departed', models.BooleanField(default=False)),
                ('advance_received', models.BooleanField(default=False)),
                ('arrived', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('pod_received', models.BooleanField(default=False)),
                ('balance_paid', models.BooleanField(default=False)),
                ('lr_no_b', models.BooleanField(default=False)),
                ('lr_no', models.CharField(blank=True, max_length=200, null=True)),
                ('transporter_paid', models.BooleanField(default=False)),
                ('customer_paid', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('vehicle_placed_at', models.DateTimeField(blank=True, null=True)),
                ('live_tracking_at', models.DateTimeField(blank=True, null=True)),
                ('fleet_departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='onepage_order.order')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tracking_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onepage_order.tracking')),
            ],
        ),
    ]
