# Generated by Django 5.2 on 2026-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_order', '0005_order_gst_amount_order_reference_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
