# Generated by Django 5.2 on 2026-04-13 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exist_cus_Vehicle',
            new_name='ExistingCustomerVehicle',
        ),
        migrations.RenameModel(
            old_name='Manual_Order',
            new_name='ManualOrder',
        ),
    ]
