# Generated by Django 5.2 on 2026-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0003_alter_manualorder_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
