# Generated by Django 5.2 on 2026-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0004_alter_manualorder_order_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistingCustomerVehicle',
        ),
    ]
