# Generated by Django 5.2 on 2026-07-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0041_vehicle_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_reference', models.CharField(max_length=100, unique=True)),
                ('driver_mobile', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sms_sent', 'SMS Sent'), ('active', 'Active'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('consent_received', models.BooleanField(default=False)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_accuracy', models.FloatField(default=0)),
                ('last_location', models.CharField(blank=True, max_length=300)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_session', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_reference', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='live_tracking.trackingsession')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='live_tracking.trackingsession')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('sms_reference', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_tracking.trackingsession')),
            ],
        ),
    ]
