# Generated by Django 5.2 on 2026-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('request_url', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='apitoken',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livelocation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livelocation',
            name='location_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='livelocation',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smslog',
            name='api_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='consent_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='entity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='operator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('consent_sent', 'Consent Sent'), ('consent_received', 'Consent Received'), ('tracking_active', 'Tracking Active'), ('tracking_stopped', 'Tracking Stopped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='TrackingSMS',
        ),
    ]
