# Generated by Django 5.2 on 2026-07-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsession',
            name='entity_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
