# Generated by Django 5.2 on 2026-07-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking', '0002_alter_trackingsession_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingsession',
            name='last_accuracy',
        ),
        migrations.RemoveField(
            model_name='trackingsession',
            name='last_latitude',
        ),
        migrations.RemoveField(
            model_name='trackingsession',
            name='last_longitude',
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='location_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='last_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('stopped', 'Stopped'), ('license_hold', 'License Hold'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
