# Generated by Django 5.2 on 2026-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking', '0003_remove_trackingsession_last_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
