# Generated by Django 5.2 on 2026-08-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking', '0004_alter_trackingsession_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsession',
            name='status',
            field=models.CharField(choices=[('not_enabled', 'Not Enabled'), ('imported', 'Imported'), ('sms_sent', 'SMS Sent'), ('consent_received', 'Consent Received'), ('waiting_location', 'Waiting Location'), ('active', 'Live Tracking'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('deleted', 'Deleted'), ('license_hold', 'License Hold'), ('expired', 'Consent Expired'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
