# Generated by Django 5.2 on 2026-04-17 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_remove_manual_order_customer_and_more'),
        ('vehicles', '0004_vehicle_ftl_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vehicle_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vehicle_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vehicle_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('customer', 'Customer'), ('vehicle', 'Vehicle')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('stage', models.CharField(choices=[('advance', 'Advance'), ('balance', 'Balance'), ('after_delivery', 'After Delivery'), ('after_document', 'After Document'), ('full', 'Full Payment')], default='full', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
