# Generated by Django 5.2 on 2026-04-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_banktransaction'),
        ('enquiries', '0017_enquiry_cancel_reason'),
        ('vehicles', '0004_vehicle_ftl_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('customer', 'Customer'), ('vehicle', 'Vehicle'), ('bank', 'Bank')], max_length=20)),
                ('ref_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('advance', 'Advance'), ('expense', 'Expense'), ('correction', 'Correction')], max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiries.enquiry')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
