# Generated by Django 5.2 on 2026-04-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ledgerentry'),
        ('orders', '0008_remove_manual_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerentry',
            old_name='customer',
            new_name='enquiry',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='ref_type',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='debit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
