# Generated by Django 5.2 on 2026-04-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_customer_ledgerentry_enquiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerentry',
            old_name='entry_type',
            new_name='account_type',
        ),
    ]
