# Generated by Django 5.2 on 2026-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_entry_type_ledgerentry_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletransaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicletransaction',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('advance', 'Advance Payment'), ('balance', 'Balance Payment'), ('fuel', 'Fuel'), ('driver_advance', 'Driver Advance'), ('toll', 'Toll'), ('rent', 'Vehicle Rent'), ('maintenance', 'Maintenance')], max_length=30),
        ),
    ]
