# Generated by Django 5.2 on 2026-06-03 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vehicletransaction_payment_mode_and_more'),
        ('enquiries', '0023_enquiry_customer_enquiry_customer_code'),
        ('vehicles', '0036_alter_tracking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='enquiries.enquiry'),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('invoice', 'Invoice Raised'), ('advance', 'Advance Received'), ('payment', 'Payment Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vehicle', 'Vehicle'), ('bank', 'Bank'), ('expense', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicletransaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('advance', 'Advance Payment'), ('balance', 'Balance Payment'), ('fuel', 'Fuel'), ('driver_advance', 'Driver Advance'), ('toll', 'Toll'), ('maintenance', 'Maintenance'), ('rent', 'Vehicle Rent'), ('others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicletransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vehicles.vehicle'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('office', 'Office Expense'), ('salary', 'Salary'), ('rent', 'Office Rent'), ('internet', 'Internet'), ('electricity', 'Electricity'), ('misc', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
