# Generated by Django 5.2 on 2026-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ledgerentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicletransaction',
            name='utr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
