# Generated by Django 5.2 on 2026-06-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_vehicletransaction_status_vehicletransaction_utr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
