# Generated by Django 5.2 on 2026-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_vehicletransaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customertransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='account_type',
            field=models.CharField(blank=True, choices=[('ltd', 'LTD'), ('proprietor', 'Proprietor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='payment_against',
            field=models.CharField(blank=True, choices=[('advance', 'Advance'), ('balance', 'Balance'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='transaction_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI')], max_length=20, null=True),
        ),
    ]
