# Generated by Django 5.2 on 2026-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customertransaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='transaction_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
