# Generated by Django 5.2 on 2026-07-30 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('orders', '0013_order_kms'),
        ('vehicles', '0041_vehicle_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('advance', 'Advance'), ('balance', 'Balance'), ('fuel', 'Fuel'), ('driver_advance', 'Driver Advance'), ('brokerage', 'Brokerage'), ('other', 'Other')], max_length=20)),
                ('payment_mode', models.CharField(choices=[('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI')], max_length=20)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=250)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UPITransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('payer_vpa', models.CharField(blank=True, max_length=100)),
                ('payee_vpa', models.CharField(blank=True, max_length=100)),
                ('qr_string', models.TextField(blank=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
