# Generated by Django 5.2 on 2026-04-03 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pickups', models.IntegerField(default=1)),
                ('deliveries', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('tonnage', models.FloatField(blank=True, null=True)),
                ('dimension_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('breadth', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('expected_rate', models.FloatField(blank=True, null=True)),
                ('gstbill', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('origin_pincode', models.CharField(max_length=6)),
                ('destination', models.CharField(max_length=255)),
                ('destination_pincode', models.CharField(max_length=6)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='enquiries.enquiry')),
            ],
        ),
    ]
