# Generated by Django 5.2 on 2026-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='dimension_unit',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
