# Generated by Django 5.2 on 2026-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_remove_enquiry_dimension_unit_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='dimension_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
