# Generated by Django 5.2 on 2026-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_enquiry_dimension_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='Waiting For Pitching', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiryroute',
            name='destination_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryroute',
            name='origin_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
