# Generated by Django 5.2 on 2026-04-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_alter_enquiry_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='routes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EnquiryRoute',
        ),
    ]
