# Generated by Django 5.2 on 2026-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_remove_enquiry_status_enquiry_routes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='gstbill',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='routes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
