# Generated by Django 5.2 on 2026-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_alter_enquiry_gstbill_alter_enquiry_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gstbill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
