# Generated by Django 5.2 on 2026-04-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_enquiry_material_alter_enquiry_gstbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='approval_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
