# Generated by Django 5.2 on 2026-04-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_enquiry_approval_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
