# Generated by Django 5.2 on 2026-04-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_enquiry_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='approval_price',
            new_name='approval_rate',
        ),
    ]
