# Generated by Django 5.2 on 2026-04-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_rename_approval_price_enquiry_approval_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
