# Generated by Django 5.2 on 2026-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_enquiry_enquiry_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='vehicle_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
