# Generated by Django 5.2 on 2026-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0012_enquiry_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='kms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
