# Generated by Django 5.2 on 2026-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0013_enquiry_kms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='vehicle_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
