# Generated by Django 5.2 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0014_alter_enquiry_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='pitch1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pitch2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pitch3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
