# Generated by Django 5.2 on 2026-04-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0015_enquiry_pitch1_enquiry_pitch2_enquiry_pitch3'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_converted_to_order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
