# Generated by Django 5.2 on 2026-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_enquiry_is_converted_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
