# Generated by Django 5.2 on 2026-04-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0017_enquiry_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Open Body 9 Ft', 'Open Body 9 Ft'), ('Open Body 10 Ft', 'Open Body 10 Ft'), ('Open Body 12 Ft', 'Open Body 12 Ft'), ('Open Body 14 Ft', 'Open Body 14 Ft'), ('Open Body 16 Ft', 'Open Body 16 Ft'), ('Open Body 17 Ft', 'Open Body 17 Ft'), ('Open Body 20 Ft', 'Open Body 20 Ft'), ('Open Body 24 Ft', 'Open Body 24 Ft'), ('Container 9 Ft', 'Container 9 Ft'), ('Container 10 Ft', 'Container 10 Ft'), ('Container 12 Ft', 'Container 12 Ft'), ('Container 14 Ft', 'Container 14 Ft'), ('Container 16 Ft', 'Container 16 Ft'), ('Container 17 Ft', 'Container 17 Ft'), ('Container 20 Ft', 'Container 20 Ft'), ('Container 24 Ft', 'Container 24 Ft'), ('Container 32 Ft', 'Container 32 Ft'), ('Flat Low Bed 20 Ft', 'Flat Low Bed 20 Ft'), ('Flat Low Bed 32 Ft', 'Flat Low Bed 32 Ft'), ('Flat Low Bed 40 Ft', 'Flat Low Bed 40 Ft'), ('Flat High Bed 20 Ft', 'Flat High Bed 20 Ft'), ('Flat High Bed 32 Ft', 'Flat High Bed 32 Ft'), ('Flat High Bed 40 Ft', 'Flat High Bed 40 Ft'), ('JCB', 'JCB'), ('ODC', 'ODC'), ('Torres 6 Wheels', 'Torres 6 Wheels'), ('Torres 10 Wheels', 'Torres 10 Wheels'), ('Torres 12 Wheels', 'Torres 12 Wheels'), ('Torres 14 Wheels', 'Torres 14 Wheels'), ('Torres 16 Wheels', 'Torres 16 Wheels')], max_length=100, null=True),
        ),
    ]
