# Generated by Django 5.2 on 2026-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0019_enquiry_confirmed_at_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
