# Generated by Django 5.2 on 2026-05-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0021_alter_enquiry_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='volumetric_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
