# Generated by Django 5.2 on 2026-06-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('enquiries', '0022_enquiry_volume_enquiry_volumetric_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='customers.excustomer'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
