# Generated by Django 5.2 on 2026-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0024_alter_enquiry_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='pitch1_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pitch2_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pitch3_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
