# Generated by Django 5.2 on 2026-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0025_enquiry_pitch1_remarks_enquiry_pitch2_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='disagree_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='disagree_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
