# Generated by Django 5.2 on 2026-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0026_enquiry_disagree_rate_enquiry_disagree_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Open Body 9 Ft', 'Open Body 9 Ft'), ('Open Body 10 Ft', 'Open Body 10 Ft'), ('Open Body 12 Ft', 'Open Body 12 Ft'), ('Open Body 14 Ft', 'Open Body 14 Ft'), ('Open Body 16 Ft', 'Open Body 16 Ft'), ('Open Body 17 Ft', 'Open Body 17 Ft'), ('Open Body 19 Ft', 'Open Body 19 Ft'), ('Open Body 20 Ft', 'Open Body 20 Ft'), ('Open Body 24 Ft', 'Open Body 24 Ft'), ('Container 9 Ft', 'Container 9 Ft'), ('Container 10 Ft', 'Container 10 Ft'), ('Container 12 Ft', 'Container 12 Ft'), ('Container 14 Ft', 'Container 14 Ft'), ('Container 16 Ft', 'Container 16 Ft'), ('Container 17 Ft', 'Container 17 Ft'), ('Container 19 Ft', 'Container 19 Ft'), ('Container 20 Ft', 'Container 20 Ft'), ('Container 24 Ft', 'Container 24 Ft'), ('Container 32 Ft', 'Container 32 Ft'), ('Trailer Flat Low Bed 20 Ft', 'Trailer Flat Low Bed 20 Ft'), ('Trailer Flat Low Bed 32 Ft', 'Trailer Flat Low Bed 32 Ft'), ('Trailer Flat Low Bed 40 Ft', 'Trailer Flat Low Bed 40 Ft'), ('Trailer Flat High Bed 20 Ft', 'Trailer Flat High Bed 20 Ft'), ('Trailer Flat High Bed 32 Ft', 'Trailer Flat High Bed 32 Ft'), ('Trailer Flat High Bed 40 Ft', 'Trailer Flat High Bed 40 Ft'), ('JCB', 'JCB'), ('ODC', 'ODC'), ('TATA ACE', 'Tata Ace 7 Ft'), ('TATA 407', 'Tata 407 10 to 12 Ft'), ('Bolero PickUP', 'Bolero Pickup 8 to 10 Ft'), ('Dost 8 to 9 Ft', 'Dost 8 to 9 Ft'), ('BadaDost 10 Ft', 'BadaDost 10 Ft'), ('Taurus 6 Wheels', 'Taurus 6 Wheels'), ('Taurus 10 Wheels', 'Taurus 10 Wheels'), ('Taurus 12 Wheels', 'Taurus 12 Wheels'), ('Taurus 14 Wheels', 'Taurus 14 Wheels'), ('Taurus 16 Wheels', 'Taurus 16 Wheels')], max_length=100, null=True),
        ),
    ]
