# Generated by Django 5.2 on 2026-06-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excustomer',
            name='creatd_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
