# Generated by Django 5.2 on 2026-06-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_excustomer_creatd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excustomer',
            old_name='creatd_by',
            new_name='created_by',
        ),
    ]
