# Generated by Django 5.2 on 2026-06-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_creatd_by_excustomer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excustomer',
            name='state_code',
        ),
    ]
