# Generated by Django 5.2 on 2026-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('it', 'IT'), ('sales', 'Sales'), ('fleet', 'Fleet'), ('support', 'Support'), ('accounts', 'Accounts')], max_length=20),
        ),
    ]
