# Generated by Django 5.2 on 2026-05-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Superadmin'), ('sales', 'Sales'), ('fleet', 'Fleet'), ('support', 'Support'), ('accounts', 'Accounts')], max_length=20),
        ),
    ]
