# Generated by Django 5.2 on 2026-04-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_placed', models.BooleanField(default=False)),
                ('vehicle_document', models.BooleanField(default=False)),
                ('invoice_eway', models.BooleanField(default=False)),
                ('advance_to_fleet', models.BooleanField(default=False)),
                ('fleet_departed', models.BooleanField(default=False)),
                ('advance_received', models.BooleanField(default=False)),
                ('arrived', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('pod_received', models.BooleanField(default=False)),
                ('transporter_paid', models.BooleanField(default=False)),
                ('customer_paid', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_number', models.CharField(max_length=15)),
                ('owner_number', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brokerage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upi_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('ac_type', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_app', models.CharField(choices=[('phonepe', 'PhonePe'), ('gpay', 'Google Pay'), ('paytm', 'Paytm'), ('other', 'Other')], default='phonepe', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='orders.order')),
            ],
        ),
    ]
