# Generated by Django 5.2 on 2026-04-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_tracking_arrived_at_tracking_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='upi_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
