# Generated by Django 5.2 on 2026-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ftl_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
