# Generated by Django 5.2 on 2026-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_ftl_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='loading',
            new_name='loading_unloading',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='halting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='upi_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
