# Generated by Django 5.2 on 2026-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_loading_vehicle_loading_unloading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='lr_no',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
