# Generated by Django 5.2 on 2026-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_tracking_lr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='lr_no_b',
            field=models.BooleanField(default=False),
        ),
    ]
