# Generated by Django 5.2 on 2026-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_tracking_lr_no_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_reassign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
