# Generated by Django 5.2 on 2026-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_vehicle_reassign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bank_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.CharField(blank=True, choices=[('directors', 'Directors'), ('transporters', 'Transporters'), ('brokers', 'Brokers'), ('drivers', 'Drivers'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
