# Generated by Django 5.2 on 2026-04-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_bank_verified_vehicle_bank_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tracking_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.tracking')),
            ],
        ),
    ]
