# Generated by Django 5.2 on 2026-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_trackingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('transporters', 'Transporters'), ('brokers', 'Brokers'), ('drivers', 'Drivers'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
