# Generated by Django 5.2 on 2026-05-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_credit_date_order_credit_days_order_due_date'),
        ('vehicles', '0011_alter_vehicle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='halting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='orders.order'),
        ),
    ]
