# Generated by Django 5.2 on 2026-05-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_credit_date_order_credit_days_order_due_date'),
        ('vehicles', '0012_alter_vehicle_halting_alter_vehicle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='orders.order'),
        ),
    ]
