# Generated by Django 5.2 on 2026-05-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_vehicle_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
