# Generated by Django 5.2 on 2026-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_vehicle_approval_name_vehicle_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
