# Generated by Django 5.2 on 2026-05-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0004_alter_manualorder_order_no'),
        ('orders', '0013_order_kms'),
        ('vehicles', '0019_alter_vehicle_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='manual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='manual_order.manualorder'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='manual_order.manualorder'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='upi_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
