# Generated by Django 5.2 on 2026-05-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_tracking_manual_order_vehicle_manual_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manual_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='manual_order.manualorder'),
        ),
    ]
