# Generated by Django 5.2 on 2026-05-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_vehicle_manual_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='order_type',
            field=models.CharField(choices=[('crm', 'CRM Order'), ('manual', 'Manual Order')], default='crm', max_length=10),
        ),
    ]
