# Generated by Django 5.2 on 2026-05-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_vehicle_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='manual_order.manualorder'),
        ),
    ]
