# Generated by Django 5.2 on 2026-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_alter_vehicle_manual_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('vehicle_placed', 'Vehicle Placed'), ('vehicle_document', 'Vehicle Document'), ('invoice_eway', 'Invoice / E-way'), ('advance_to_fleet', 'Advance To Fleet'), ('fleet_departed', 'Fleet Departed'), ('advance_received', 'Advance Received'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('pod_received', 'POD Received'), ('settled', 'Settled')], default='vehicle_placed', max_length=50),
        ),
    ]
