# Generated by Django 5.2 on 2026-05-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0006_manualorder_vehicle_assign_date_and_more'),
        ('vehicles', '0025_vehicle_is_overpaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_overpaid',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manual_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='manual_order.manualorder'),
        ),
    ]
