# Generated by Django 5.2 on 2026-05-31 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_kms'),
        ('vehicles', '0026_remove_vehicle_is_overpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='orders.order'),
        ),
    ]
