# Generated by Django 5.2 on 2026-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_kms'),
        ('vehicles', '0027_alter_vehicle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='vehicle',
                to='orders.order',
            ),
        ),
    ]