# Generated by Django 5.2 on 2026-06-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0006_manualorder_vehicle_assign_date_and_more'),
        ('orders', '0013_order_kms'),
        ('vehicles', '0027_alter_vehicle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='manual_order.manualorder'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='orders.order'),
        ),
    ]
