# Generated by Django 5.2 on 2026-06-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_kms'),
        ('vehicles', '0028_alter_vehicle_manual_order_alter_vehicle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='approval_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='approval_reason',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='approval_required',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='manual_order',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='margin_percentage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='profit_amount',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='halting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.CharField(blank=True, choices=[('directors', 'Directors'), ('transporters', 'Transporters'), ('brokers', 'Brokers'), ('drivers', 'Drivers'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='upi_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
