# Generated by Django 5.2 on 2026-06-02 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_order', '0006_manualorder_vehicle_assign_date_and_more'),
        ('vehicles', '0029_remove_vehicle_approval_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='manual_order.manualorder'),
        ),
    ]
