# Generated by Django 5.2 on 2026-06-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_kms'),
        ('vehicles', '0030_vehicle_manual_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manual_order',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='orders.order'),
        ),
    ]
