# Generated by Django 5.2 on 2026-06-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_kms'),
        ('vehicles', '0033_alter_vehicle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='orders.order'),
        ),
    ]
