# Generated by Django 5.2 on 2026-06-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0034_alter_vehicle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='manual_order',
        ),
    ]
