# Generated by Django 5.2 on 2026-06-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0036_alter_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_overpaid',
            field=models.BooleanField(default=False),
        ),
    ]
