# Generated by Django 5.2 on 2026-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0037_vehicle_is_overpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracking',
            name='balance_to_fleet',
            field=models.BooleanField(default=False),
        ),
    ]
