# Generated by Django 5.2 on 2026-06-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0038_tracking_balance_paid_tracking_balance_to_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('vehicle_placed', 'Vehicle Placed'), ('vehicle_document', 'Vehicle Document'), ('invoice_eway', 'Invoice / E-way'), ('advance_to_fleet', 'Advance To Fleet'), ('fleet_departed', 'Fleet Departed'), ('balance_trans_fleet', 'Balance Transfer To Fleet'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('pod_received', 'POD Received'), ('settled', 'Settled'), ('lr_generated', 'LR Generated')], default='vehicle_placed', max_length=50),
        ),
    ]
