# Generated by Django 5.2 on 2026-06-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0039_alter_tracking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='order',
        ),
    ]
