# Generated by Django 5.2 on 2026-07-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_kms'),
        ('vehicles', '0040_remove_vehicle_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='orders.order'),
        ),
    ]
