# Generated by Django 5.2 on 2026-04-03 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('final_rate', models.FloatField(blank=True, null=True)),
                ('loading_unloading', models.FloatField(default=0)),
                ('halting_charges', models.FloatField(default=0)),
                ('gst_percent', models.FloatField(default=0)),
                ('total_rate', models.FloatField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Order Confirmed'), ('cancelled', 'Cancelled'), ('rate_mismatch', 'Rate Mismatch')], default='draft', max_length=20)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('advance', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('credit_days', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='enquiries.enquiry')),
            ],
        ),
    ]
