# Generated by Django 5.2 on 2026-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin',
        ),
        migrations.AddField(
            model_name='order',
            name='routes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
