# Generated by Django 5.2 on 2026-04-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_enquiry_is_converted_to_order'),
        ('orders', '0003_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='enquiries.enquiry'),
        ),
    ]
