# Generated by Django 5.2 on 2026-04-11 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_date_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('origin', models.TextField(blank=True)),
                ('destination', models.TextField(blank=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_description', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('pieces', models.IntegerField(default=0)),
                ('tonnage', models.FloatField(default=0)),
                ('expected_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('credit', 'Credit')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.manual_order')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_freight', models.FloatField(default=0)),
                ('extra_charges', models.FloatField(default=0)),
                ('advance_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.manual_order')),
            ],
        ),
    ]
