# Generated by Django 5.2 on 2026-04-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customer_manual_order_payment_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='exist_cus_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_number', models.CharField(max_length=15)),
                ('owner_number', models.CharField(max_length=15)),
                ('freight_amount', models.FloatField(default=0)),
                ('upi_app', models.CharField(blank=True, choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exvehicles', to='orders.manual_order')),
            ],
        ),
    ]
