# Generated by Django 5.2 on 2026-04-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_exist_cus_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual_order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='exist_cus_vehicle',
            name='order',
        ),
        migrations.RemoveField(
            model_name='manual_order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='exist_cus_Vehicle',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Manual_Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
