# Generated by Django 5.2 on 2026-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_manual_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
