# Generated by Django 5.2 on 2026-04-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicle_place_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
