# Generated by Django 5.2 on 2026-04-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_vehicle_place_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vehicle_place_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
