# Generated by Django 5.2 on 2026-04-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_vehicle_place_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
