# Generated by Django 5.2 on 2026-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_credit_date_order_credit_days_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
